### ISSUE TITLE
Add missing attachments option

### ISSUE THREAD

**Issue by wiifree** [autotelic/fastify-mail#29]
In the [createMessage function](https://github.com/autotelic/fastify-mail/blob/789f82b29ad935285df2fe6a446731eb3139d7d6/index.js#L58) i miss the functionality to add some attachments. Based on the [Nodemailer config](https://nodemailer.com/message/) you only need to add the attachments variable.

**Comment by philberryman** [comment]
Thanks @wiifree - I'll look at adding this. As you say - it should be quite straight forward.

**Comment by wiifree** [comment]
@philberryman I opened a pull request #30 that should solve this missing feature.
