### ISSUE TITLE
bubble up renderTemplate errors

### ISSUE THREAD

**Issue by eadmundo** [autotelic/fastify-mail#34]
currently we just return null https://github.com/autotelic/fastify-mail/blob/main/index.js#L93

**Comment by megquirk** [comment]
fixed here: https://github.com/autotelic/fastify-mail/pull/33/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L91-R103

**Comment by megquirk** [comment]
Closed with #33
